name: Publish Logseq
on: [push]
permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: logseq/publish-spa@v0.3.0
        with:
          graph-directory: .          # 你的图谱根目录
          output-directory: www
      - name: Add nojekyll
        run: touch www/.nojekyll
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: www
